server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:loandb
    driverClassName: org.h2.Driver
    username: admin
    password: 1234
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  
  config:
    import: "optional:configserver:http://localhost:8071"
  application:
    name: "loans"  
#  profiles:
#    active: "prod"
#  datasource:  
#    driver-class-name: org.postgresql.Driver
#    password: root
#    url: jdbc:postgresql://localhost:5432/loansdb
#    username: jagadesh    
#  rabbitmq:
#    host: localhost
#    port: 5672  
#    username: guest
#    password: guest
#    
    
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/  
      
info:
  app:
    name: "loans-1"
    description: "Zetta Bank Loans Application"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true