server:
  port: 9000
spring:
#  datasource:
#    url: jdbc:h2:mem:cardsdb
#    driverClassName: org.h2.Driver
#    username: admin
#    password: 1234
#  h2:
#    console:
#      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:  
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:mem:accountsdb
#      username: admin
#      password: 123 
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/cardsdb
    username: jagadesh  
    
    
  config:
    import: "optional:configserver:http://localhost:8071"
  application:
    name: "cards"
#  profiles:
#    active: "qa"
#  datasource:  
#    driver-class-name: org.postgresql.Driver
#    password: root
#    url: jdbc:postgresql://localhost:5432/cardsdb
#    username: jagadesh  
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest 
#    
    
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/  
      
info:
  app:
    name: "cards"
    description: "Zetta Bank Cards Application"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true